# Generated by Django 5.1.4 on 2024-12-31 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_objeto', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('malo', 'Malo')], default='nuevo', max_length=12)),
                ('curso', models.CharField(choices=[('sin_empezar', 'Sin empezar'), ('empezado', 'Empezado'), ('terminado', 'Terminado')], default='sin_empezar', max_length=12)),
                ('fecha_salida', models.DateField()),
                ('tags', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('foto', models.CharField(max_length=200)),
                ('edicion', models.CharField(max_length=100)),
                ('editorial', models.CharField(max_length=100)),
                ('volumen', models.IntegerField()),
                ('autor', models.CharField(max_length=100)),
                ('genero', models.CharField(max_length=100)),
                ('altura', models.IntegerField()),
                ('marca', models.CharField(max_length=100)),
                ('plataforma', models.CharField(max_length=100)),
                ('compania', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoObjeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_objeto', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeria', models.CharField(max_length=200)),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekapp.inventario')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_tipoobjeto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekapp.tipoobjeto'),
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='geekapp.users'),
        ),
    ]
