# Generated by Django 5.1.1 on 2025-01-08 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TipoObjeto',
        ),
    ]
