# Generated by Django 5.1.7 on 2025-03-26 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0002_albumimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventario',
            name='foto',
        ),
    ]
