# Generated by Django 5.1.7 on 2025-03-27 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0004_remove_inventario_tags_alter_inventario_tipo_objeto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='tipo_objeto',
            field=models.CharField(choices=[('libro', 'Libro'), ('manga', 'Manga'), ('comic', 'Cómic'), ('figura', 'Figura'), ('consola', 'Consola'), ('videojuego', 'Videojuego'), ('otro', 'Otro')], default='libro', max_length=12),
        ),
    ]
