# Generated by Django 5.1.7 on 2025-03-27 18:32

import taggit.managers
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0005_alter_inventario_tipo_objeto'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='curso',
            field=models.CharField(choices=[('sin_empezar', 'Sin empezar'), ('empezado', 'Empezado'), ('terminado', 'Terminado')], max_length=12),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
    ]
