# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0008_alter_inventario_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='estado',
            field=models.CharField(choices=[('nuevo', 'Nuevo'), ('bueno', 'Bueno'), ('malo', 'Malo')], max_length=12),
        ),
        migrations.AlterField(
            model_name='inventario',
            name='tipo_objeto',
            field=models.CharField(choices=[('libro', 'Libro'), ('manga', 'Manga'), ('comic', 'Cómic'), ('figura', 'Figura'), ('consola', 'Consola'), ('videojuego', 'Videojuego'), ('otro', 'Otro')], max_length=12),
        ),
    ]
