# Generated by Django 5.1.7 on 2025-03-27 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0009_alter_inventario_estado_alter_inventario_tipo_objeto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventario',
            name='curso',
            field=models.CharField(blank=True, choices=[('sin_empezar', 'Sin empezar'), ('empezado', 'Empezado'), ('terminado', 'Terminado')], max_length=12),
        ),
    ]
