# Generated by Django 5.1.7 on 2025-05-07 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0010_alter_inventario_curso'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='fecha_compra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
