# Generated by Django 5.1.7 on 2025-06-03 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geekapp', '0011_inventario_fecha_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='public_token',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
